name: tagged-release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  tagged-release:
    name: Tagged release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build main.js
        run: npm run build

      - name: Generate changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body: ${{ steps.changelog.outputs.changes }}
          files: main.js
